defaults:
  - _self_

num_envs: 10
generate_map: False
env_name: warehouse

sensor:
  camera:
    pos: [0.3, 0.0, 0.1]
    rot: [1.0, 0.0, 0.0, 0.0]
  lidar:
    pos: [0.2, 0.0, 0.3]
    rot: [1.0, 0.0, 0.0, 0.0]

envs:
  warehouse:
    turret:
      enabled: false
      count: 0
      usd_path: ""
      instances:
  full-warehouse:
    turret:
      enabled: false
      count: 0
      usd_path: ""
      instances:
  stage:
    turret:
      enabled: true
      count: 3
      usd_path: "/home/loe/workspace/github/SpotATS_ws/ATS_IsaacSim/Main/ATS_Enviroment/ATS_01.usd"
      instances:
        - pos: [-9.0, -14.4, 4.0]
          rot: [0.9304, 0.0, 0.0, -0.3665]
          scale: [4.0, 4.0, 4.0]
        - pos: [-9.0, -11.4, 4.0]
          rot: [0.4226, 0.0, 0.0, 0.9063]
          scale: [4.0, 4.0, 4.0]
        - pos: [2.1, -13.4, 3.5]
          rot: [0.0, 0.0, 0.0, 1.0]
          scale: [4.0, 4.0, 4.0]
          

agent_cfg_path: "config/agent.yaml"

mapping:
  enable_mapping: True    
  origin: [0.0, 0.0, 1.0]     
  lower_bound: [-40.0, -40.0, 0.1]
  upper_bound: [5.0, 5.0, 0.5] 
  cell_size: 0.05            
  output_path: "./map"    
  use_physx_geometry: True   